const CHUNK_PUBLIC_PATH = "server/app/services/page.js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_66bdff._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__ea5163._.js");
runtime.loadChunk("server/chunks/ssr/src_app_896cde._.js");
runtime.loadChunk("server/chunks/ssr/_4e14ce._.js");
runtime.loadChunk("server/chunks/ssr/src_app_62bc90._.css");
runtime.loadChunk("server/chunks/ssr/node_modules_16929d._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_3792b8._.js");
runtime.loadChunk("server/chunks/ssr/_3b8565._.js");
runtime.loadChunk("server/chunks/ssr/src_53c770._.css");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/services/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/services/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/src/app/layout.jsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/src/app/services/page.jsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
